# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration files
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path path, space-separated, executed in env.py.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to clone to slug
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be loaded that are
# not part of the sys.path
# version_locations = %(here)s/bar:%(here)s/bat:version_locations

# version path separator; defaults to 'os.pathsep'.
# Use a space to span multiple lines in a single value.
# version_path_separator = :

# the database url (overridden in env.py from settings)
sqlalchemy.url = postgresql+asyncpg://postgres:postgres@localhost:5432/sharebot_db

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
