global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 1. Prometheus Server Self Metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. FastAPI Application Metrics
  - job_name: 'sharebot-api'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:8000']
